# Generated by Django 5.2.9 on 2025-12-29 15:21

import django.db.models.deletion
import ferries.models.ferry_request
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Port Code e.g. ALG", max_length=5, unique=True
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ferries_port",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code e.g. BAL", max_length=10, unique=True
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="providers/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ferries_provider",
            },
        ),
        migrations.CreateModel(
            name="ProviderRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arrivals",
                        to="ferries.port",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departures",
                        to="ferries.port",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routes",
                        to="ferries.provider",
                    ),
                ),
            ],
            options={
                "db_table": "ferries_provider_route",
                "unique_together": {("provider", "origin", "destination")},
            },
        ),
        migrations.CreateModel(
            name="FerryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        default=ferries.models.ferry_request.generate_reference,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("round", "Round Trip"), ("oneway", "One Way")],
                        default="round",
                        max_length=10,
                    ),
                ),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("passengers_data", models.JSONField(default=dict)),
                ("vehicle_data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "accommodation",
                    models.CharField(
                        default="Seat", help_text="Seat, Cabin, etc.", max_length=50
                    ),
                ),
                (
                    "net_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("offer_sent", "Offer Sent"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "voucher",
                    models.FileField(blank=True, null=True, upload_to="vouchers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ferry_requests",
                        to="agencies.agency",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="ferries.providerroute",
                    ),
                ),
            ],
            options={
                "db_table": "ferries_request",
            },
        ),
    ]
