# Generated by Django 5.2.9 on 2026-01-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ferryrequest",
            name="admin_note",
            field=models.TextField(
                blank=True, help_text="notes from the admin to the agency", null=True
            ),
        ),
        migrations.AddField(
            model_name="ferryrequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the request for this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ferryrequest",
            name="user_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="The administrator user responsible for managing this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
