# Generated by Django 5.2.9 on 2026-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferries", "0002_ferryrequest_admin_note_ferryrequest_requested_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ferryrequest",
            name="voucher",
            field=models.FileField(blank=True, null=True, upload_to="ferry/vouchers/"),
        ),
    ]
