# Generated by Django 5.2.9 on 2026-01-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferries", "0003_alter_ferryrequest_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferryrequest",
            name="price_breakdown",
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name="RoutePriceComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pax", "Passenger"),
                            ("vehicle", "Vehicle"),
                            ("accommodation", "Installation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                (
                    "net_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_components",
                        to="ferries.providerroute",
                    ),
                ),
            ],
            options={
                "db_table": "ferries_price_component",
                "indexes": [
                    models.Index(
                        fields=["route", "category", "item_name"],
                        name="ferries_pri_route_i_b9b028_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="ferries_pri_start_d_89ea2a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="ferries.providerroute",
                    ),
                ),
            ],
            options={
                "db_table": "ferries_route_schedule",
                "ordering": ["date"],
                "unique_together": {("route", "date")},
            },
        ),
    ]
