# Generated by Django 5.2.9 on 2026-01-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferries", "0004_ferryrequest_price_breakdown_routepricecomponent_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="routepricecomponent",
            constraint=models.UniqueConstraint(
                fields=("route", "category", "item_name"),
                name="unique_price_component_per_route",
            ),
        ),
    ]
