# Generated by Django 5.2.9 on 2026-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="category",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Platform Admin Side"),
                    ("AGENCY", "Agency Client Side"),
                ],
                default="AGENCY",
                max_length=10,
            ),
        ),
    ]
