# Generated by Django 5.2.9 on 2026-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=15,
                verbose_name="Cash Balance",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, verbose_name="Credit Line"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="unpaid_hold",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
