# Generated by Django 5.2.9 on 2026-01-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0003_alter_invoice_total_amount_alter_invoiceitem_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlimithistory",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
