# Generated by Django 5.2.9 on 2025-12-30 09:38

import django.db.models.deletion
import visas.models.visa_application
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisaDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("visa_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "visa_type",
                    models.CharField(
                        help_text="e.g. Tourist, Business", max_length=100
                    ),
                ),
                (
                    "net_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Embassy Price", max_digits=10
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Selling Price",
                        max_digits=10,
                    ),
                ),
                (
                    "processing_time",
                    models.CharField(help_text="e.g. 15-20 Days", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="visa_destinations/"
                    ),
                ),
            ],
            options={
                "db_table": "visas_destination",
            },
        ),
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        default=visas.models.visa_application.generate_visa_ref,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("passport_number", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Application"),
                            ("review", "Under Review"),
                            ("appointment", "Appointment Scheduled"),
                            ("embassy", "Submitted to Embassy"),
                            ("ready", "Ready for Collection"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "embassy_appointment_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visa_applications",
                        to="agencies.agency",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="visas.visadestination",
                    ),
                ),
            ],
            options={
                "db_table": "visas_application",
            },
        ),
        migrations.CreateModel(
            name="VisaForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="visas.visadestination",
                    ),
                ),
            ],
            options={
                "db_table": "visas_form",
            },
        ),
        migrations.CreateModel(
            name="VisaFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Question text e.g. 'Mother's Name'", max_length=255
                    ),
                ),
                (
                    "field_key",
                    models.CharField(
                        help_text="Unique key for code e.g. 'mother_name'",
                        max_length=50,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("number", "Number Input"),
                            ("date", "Date Picker"),
                            ("select", "Dropdown Select"),
                            ("checkbox", "Checkbox (Yes/No)"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated options for dropdowns",
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "order_index",
                    models.IntegerField(
                        default=0, help_text="Order to display in the form"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="visas.visaform",
                    ),
                ),
            ],
            options={
                "db_table": "visas_form_field",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="VisaApplicationAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="visas.visaapplication",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visas.visaformfield",
                    ),
                ),
            ],
            options={
                "db_table": "visas_application_answer",
            },
        ),
        migrations.CreateModel(
            name="VisaRequiredDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="visas.visadestination",
                    ),
                ),
            ],
            options={
                "db_table": "visas_required_document",
            },
        ),
        migrations.CreateModel(
            name="VisaApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="visa_uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to="visas.visaapplication",
                    ),
                ),
                (
                    "required_doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="visas.visarequireddocument",
                    ),
                ),
            ],
            options={
                "db_table": "visas_application_document",
            },
        ),
    ]
