# Generated by Django 5.2.9 on 2026-01-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0002_remove_visaformfield_field_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaapplication",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
