# Generated by Django 5.2.9 on 2026-01-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0003_alter_visaapplication_admin_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New Application"),
                    ("review", "Under Review"),
                    ("appointment", "Appointment Scheduled"),
                    ("embassy", "Submitted to Embassy"),
                    ("ready", "Ready for Collection"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
