# Generated by Django 5.2.9 on 2026-01-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0004_alter_visaapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="visadestination",
            name="conditions",
            field=models.TextField(
                blank=True, help_text="Visa conditions with bullet points", null=True
            ),
        ),
    ]
