# Generated by Django 5.2.9 on 2026-01-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0005_visadestination_conditions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visaapplication",
            name="apply_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who apply the visa.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apply_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="user_admin",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin user who treat the application.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
