# Generated by Django 5.2.9 on 2026-01-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0006_visaapplication_apply_by_visaapplication_user_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="visaapplication",
            name="visa_doc",
            field=models.FileField(
                blank=True, null=True, upload_to="visa_uploads/ready/"
            ),
        ),
    ]
