# Generated by Django 5.2.9 on 2025-12-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="agency_logos/"),
                ),
                (
                    "rc_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Trade Registry"
                    ),
                ),
                (
                    "rc_document",
                    models.FileField(blank=True, null=True, upload_to="legal_docs/"),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agencies_agency",
            },
        ),
        migrations.CreateModel(
            name="AgencyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="blue", help_text="CSS color name or hex", max_length=20
                    ),
                ),
            ],
            options={
                "db_table": "agencies_tag",
            },
        ),
    ]
