# Generated by Django 5.2.9 on 2026-01-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="credit_limit",
        ),
    ]
